package br.com.iworkout.db.entity;


import com.j256.ormlite.dao.ForeignCollection;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.field.ForeignCollectionField;

public class Exercicio {

    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    int id;
    @DatabaseField(index = true)
    String nome;
    @ForeignCollectionField(eager = false)
    ForeignCollection<Musculo> musculos;

    public Exercicio() {
        // needed by ormlite
    }

    public Exercicio (String nome){
        this.nome = nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getNome() {
        return nome;
    }
}
