package br.com.iworkout.db.entity;


import com.j256.ormlite.field.DatabaseField;

public class Musculo {

    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    int id;
    @DatabaseField(index = true)
    String nome;

    Musculo() {
        // needed by ormlite
    }
}
