package br.com.iworkout.db.entity;


import com.j256.ormlite.field.DatabaseField;

public class Musculo {

    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    int id;
    @DatabaseField(index = true)
    String nome;

    public Musculo() {
        // needed by ormlite
    }

    public Musculo (String nome){
        this.nome = nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getNome() {
        return nome;
    }
}
